import { SvgMap } from './types';
import { writeIfChanged } from './write-if-changed';

export const writeTypes = async (filePath: string, svgMap: SvgMap): Promise<void> => {
  const iconNames = [...svgMap.keys()];
  const content = [
    '/* eslint-disable */',
    '',
    '// This file is autogenerated. Do not commit to source control.',
    '',
    'export type IconName = (typeof iconNames)[number];',
    '',
    'export const iconNames = [',
    ...iconNames.map(name => `  '${name}',`),
    '] as const;',
    '',
  ].join('\n');

  await writeIfChanged(filePath, content);
};
