import { SvgMap } from './types';
import { writeIfChanged } from './write-if-changed';

export const writeTypes = async (filePath: string, svgMap: SvgMap): Promise<void> => {
  // Sorted because svgMap insertion order depends on file-read completion order,
  // and this file is meant to be committed — unstable ordering would cause diff churn.
  const iconNames = [...svgMap.keys()].sort();
  // Since the file is committed, formatters/linters will try to rewrite it and every
  // rebuild would undo them again — suppress the common ones so it stays byte-stable.
  const content = [
    '/* eslint-disable */',
    '// biome-ignore-all format: autogenerated file — kept byte-stable across rebuilds',
    '// biome-ignore-all lint: autogenerated file — kept byte-stable across rebuilds',
    '',
    '// This file is autogenerated. Keep it committed so typechecking works without a build.',
    '',
    'export type IconName = (typeof iconNames)[number];',
    '',
    'export const iconNames = [',
    ...iconNames.map(name => `\t'${name}',`),
    '] as const;',
    '',
  ].join('\n');

  await writeIfChanged(filePath, content);
};
