import { SvgMap } from './types';
import { writeIfChanged } from './write-if-changed';

export const writeTypes = async (filePath: string, svgMap: SvgMap): Promise<void> => {
  // Sorted because svgMap insertion order depends on file-read completion order,
  // and this file is meant to be committed — unstable ordering would cause diff churn.
  const iconNames = [...svgMap.keys()].sort();
  const content = [
    '/* eslint-disable */',
    '',
    '// This file is autogenerated. Keep it committed so typechecking works without a build.',
    '',
    'export type IconName = (typeof iconNames)[number];',
    '',
    'export const iconNames = [',
    ...iconNames.map(name => `  '${name}',`),
    '] as const;',
    '',
  ].join('\n');

  await writeIfChanged(filePath, content);
};
