name: Release Action

on:
  workflow_dispatch:
  push:
    branches: ['main']

jobs:
  release:
    name: Build, Tag and Release
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'workflow_dispatch' || contains(github.event.head_commit.message, '[release]') }}
    permissions:
      contents: write
      issues: write
      pull-requests: write

    steps:

      - name: Checkout source
        uses: actions/checkout@v4

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: npm

      - name: Install dependencies
        run: npm ci
        
      - name: Compile and bundle
        run: npm run build

      - name: Tag and release
        run: npx -p @semantic-release/git -p semantic-release-major-tag -p semantic-release semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}